import type { ReactNode } from 'react';
import { Glyphs } from './icons';

export type IconTone = 'teal' | 'coral' | 'ink' | 'mint' | 'sky' | 'gold' | 'violet';
export type IconGroup = 'ops' | 'parking' | 'district' | 'account' | 'system';

/** مرجع كل أيقونة — الاسم، المعنى، والمسار */
export interface IconDef {
  id: string;
  glyph: ReactNode;
  tone: IconTone;
  nameAr: string;
  nameEn: string;
  descAr: string;
  descEn: string;
  route?: string;
  group: IconGroup;
}

export const ICON_CATALOG: Record<string, IconDef> = {
  brandMark: {
    id: 'brandMark',
    glyph: Glyphs.brandMark,
    tone: 'teal',
    nameAr: 'شعار NRI',
    nameEn: 'NRI Logo',
    descAr: 'هوية بوابة موقف الحي',
    descEn: 'District parking portal identity',
    group: 'system',
  },
  home: {
    id: 'home',
    glyph: Glyphs.home,
    tone: 'teal',
    nameAr: 'الرئيسية',
    nameEn: 'Home',
    descAr: 'لوحة البداية واختصارات حسب دورك',
    descEn: 'Landing shortcuts for your role',
    route: '/',
    group: 'parking',
  },
  car: {
    id: 'car',
    glyph: Glyphs.car,
    tone: 'mint',
    nameAr: 'إشغال المبنى',
    nameEn: 'Occupancy',
    descAr: 'أماكن شاغرة ومشغولة — تحديث لحظي',
    descEn: 'Free vs occupied spaces — live',
    route: '/occupancy',
    group: 'parking',
  },
  session: {
    id: 'session',
    glyph: Glyphs.session,
    tone: 'coral',
    nameAr: 'جلسة الموقف',
    nameEn: 'Session',
    descAr: 'جلسة الوقوف الحالية والمبلغ المستحق',
    descEn: 'Current parking session and amount due',
    route: '/session',
    group: 'parking',
  },
  history: {
    id: 'history',
    glyph: Glyphs.history,
    tone: 'sky',
    nameAr: 'الإيصالات',
    nameEn: 'Receipts',
    descAr: 'سجل الجلسات والمدفوعات السابقة',
    descEn: 'Past sessions and payments',
    route: '/receipts',
    group: 'parking',
  },
  find: {
    id: 'find',
    glyph: Glyphs.find,
    tone: 'violet',
    nameAr: 'لاقي عربيتي',
    nameEn: 'Find My Car',
    descAr: 'موقع المركبة داخل المبنى',
    descEn: 'Vehicle location inside the building',
    route: '/find-car',
    group: 'parking',
  },
  card: {
    id: 'card',
    glyph: Glyphs.card,
    tone: 'gold',
    nameAr: 'الاشتراك',
    nameEn: 'Subscription',
    descAr: 'باقات وشراء وتجديد الاشتراك',
    descEn: 'Bundles, purchase, and renewal',
    route: '/subscriptions',
    group: 'parking',
  },
  calendar: {
    id: 'calendar',
    glyph: Glyphs.calendar,
    tone: 'coral',
    nameAr: 'الحجز',
    nameEn: 'Reservations',
    descAr: 'حجز مكان أو دعوة زائر',
    descEn: 'Reserve a slot or invite a guest',
    route: '/reservations',
    group: 'parking',
  },
  key: {
    id: 'key',
    glyph: Glyphs.key,
    tone: 'sky',
    nameAr: 'كود الدعوة',
    nameEn: 'Invite Code',
    descAr: 'التحقق من كود دعوة الساكن',
    descEn: 'Verify a resident invite code',
    route: '/invite',
    group: 'parking',
  },
  qr: {
    id: 'qr',
    glyph: Glyphs.qr,
    tone: 'violet',
    nameAr: 'بطاقة الدخول',
    nameEn: 'Access Pass',
    descAr: 'QR للدخول أو الاشتراك',
    descEn: 'QR for entry or subscription',
    route: '/pass',
    group: 'district',
  },
  ev: {
    id: 'ev',
    glyph: Glyphs.ev,
    tone: 'mint',
    nameAr: 'شواحن EV',
    nameEn: 'EV Chargers',
    descAr: 'محطات الشحن الكهربائي',
    descEn: 'Electric vehicle charging stations',
    route: '/ev',
    group: 'district',
  },
  bill: {
    id: 'bill',
    glyph: Glyphs.bill,
    tone: 'gold',
    nameAr: 'فواتير الحي',
    nameEn: 'District Billing',
    descAr: 'فواتير مستحقة — عرض فقط',
    descEn: 'Due invoices — view only',
    route: '/billing',
    group: 'district',
  },
  ticket: {
    id: 'ticket',
    glyph: Glyphs.ticket,
    tone: 'sky',
    nameAr: 'بلاغ الدعم',
    nameEn: 'Support Ticket',
    descAr: 'فتح بلاغ: حاجز، نفايات، صيانة…',
    descEn: 'Open ticket: barrier, waste, maintenance…',
    route: '/tickets',
    group: 'account',
  },
  user: {
    id: 'user',
    glyph: Glyphs.user,
    tone: 'teal',
    nameAr: 'حسابي',
    nameEn: 'Profile',
    descAr: 'الملف، اللغة، ومركباتي',
    descEn: 'Profile, language, and vehicles',
    route: '/profile',
    group: 'account',
  },
  dash: {
    id: 'dash',
    glyph: Glyphs.dash,
    tone: 'teal',
    nameAr: 'لوحة الإشغال',
    nameEn: 'Ops Dashboard',
    descAr: 'أرقام الإشغال لكل المباني',
    descEn: 'Occupancy numbers for all buildings',
    route: '/admin/occupancy',
    group: 'ops',
  },
  search: {
    id: 'search',
    glyph: Glyphs.search,
    tone: 'sky',
    nameAr: 'بحث اللوحة',
    nameEn: 'Plate Search',
    descAr: 'بحث جزئي عن لوحة عبر المباني',
    descEn: 'Partial plate search across buildings',
    route: '/admin/plates',
    group: 'ops',
  },
  chart: {
    id: 'chart',
    glyph: Glyphs.chart,
    tone: 'mint',
    nameAr: 'التقارير',
    nameEn: 'Reports',
    descAr: 'إيراد، إشغال، مخالفات، اشتراكات',
    descEn: 'Revenue, occupancy, violations, subs',
    route: '/admin/reports',
    group: 'ops',
  },
  timer: {
    id: 'timer',
    glyph: Glyphs.timer,
    tone: 'coral',
    nameAr: 'مخالفات السماح',
    nameEn: 'Grace Violations',
    descAr: 'جلسات تجاوزت مهلة الخروج',
    descEn: 'Sessions past exit grace period',
    route: '/admin/grace',
    group: 'ops',
  },
  support: {
    id: 'support',
    glyph: Glyphs.support,
    tone: 'violet',
    nameAr: 'بلاغات الدعم',
    nameEn: 'Support Queue',
    descAr: 'طابور بلاغات المستخدمين للمدير',
    descEn: 'User support ticket queue for admin',
    route: '/admin/tickets',
    group: 'ops',
  },
  users: {
    id: 'users',
    glyph: Glyphs.users,
    tone: 'gold',
    nameAr: 'المستخدمون',
    nameEn: 'Users',
    descAr: 'قائمة المستخدمين — قراءة فقط',
    descEn: 'User directory — read only',
    route: '/admin/users',
    group: 'ops',
  },
  usersManage: {
    id: 'usersManage',
    glyph: Glyphs.users,
    tone: 'gold',
    nameAr: 'إدارة المستخدمين',
    nameEn: 'Manage Users',
    descAr: 'إنشاء وتعديل وتفعيل المستخدمين والأدوار',
    descEn: 'Create, edit, activate users and roles',
    route: '/admin/users-manage',
    group: 'ops',
  },
  cameras: {
    id: 'cameras',
    glyph: Glyphs.find,
    tone: 'mint',
    nameAr: 'الكاميرات',
    nameEn: 'Cameras',
    descAr: 'إضافة كاميرا، ONVIF، StreamUrl و RTSP',
    descEn: 'Add camera, ONVIF, StreamUrl and RTSP',
    route: '/admin/cameras',
    group: 'ops',
  },
  settings: {
    id: 'settings',
    glyph: Glyphs.settings,
    tone: 'sky',
    nameAr: 'الإعدادات',
    nameEn: 'Settings',
    descAr: 'الكاميرات وتخطيطات العرض للمراقبة',
    descEn: 'Cameras and monitor view layouts',
    route: '/admin/settings',
    group: 'ops',
  },
  views: {
    id: 'views',
    glyph: Glyphs.grid,
    tone: 'violet',
    nameAr: 'تخطيطات العرض',
    nameEn: 'Views',
    descAr: 'شبكة الكاميرات — صفوف وأعمدة',
    descEn: 'Camera grid — rows and columns',
    route: '/admin/views',
    group: 'ops',
  },
  lpr: {
    id: 'lpr',
    glyph: Glyphs.car,
    tone: 'coral',
    nameAr: 'مراقبة LPR',
    nameEn: 'LPR Monitor',
    descAr: 'أحداث اللوحات المباشرة والسجل',
    descEn: 'Live plate events and history',
    route: '/admin/lpr',
    group: 'ops',
  },
  freePlaces: {
    id: 'freePlaces',
    glyph: Glyphs.dash,
    tone: 'mint',
    nameAr: 'تحرير الأماكن',
    nameEn: 'Free Places',
    descAr: 'تحرير السلوتات المشغولة وتحديث الإشغال مباشرة',
    descEn: 'Release occupied bays and update occupancy live',
    route: '/admin/free-places',
    group: 'ops',
  },
  gates: {
    id: 'gates',
    glyph: Glyphs.gate,
    tone: 'teal',
    nameAr: 'البوابات',
    nameEn: 'Gates',
    descAr: 'مراقبة وإدارة بوابات المداخل والمخارج',
    descEn: 'Monitor and manage entry and exit gates',
    route: '/admin/gates',
    group: 'ops',
  },
  barriers: {
    id: 'barriers',
    glyph: Glyphs.barrier,
    tone: 'sky',
    nameAr: 'الحواجز الذكية',
    nameEn: 'Smart Barriers',
    descAr: 'لوحة التحكم الفوري بذراع الحاجز والهاردوير',
    descEn: 'Real-time barrier arm control and hardware telemetry',
    route: '/admin/barriers',
    group: 'ops',
  },
  operationsCenter: {
    id: 'operationsCenter',
    glyph: Glyphs.dash,
    tone: 'coral',
    nameAr: 'مركز العمليات',
    nameEn: 'Operations Center',
    descAr: 'غرفة القيادة والتحكم اللحظي بالأجهزة والبوابات',
    descEn: 'Unified real-time command & operations cockpit',
    route: '/admin/operations-center',
    group: 'ops',
  },
  logout: {

    id: 'logout',
    glyph: Glyphs.logout,
    tone: 'coral',
    nameAr: 'خروج',
    nameEn: 'Logout',
    descAr: 'إنهاء الجلسة وتسجيل الخروج',
    descEn: 'End session and sign out',
    group: 'system',
  },
  menu: {
    id: 'menu',
    glyph: Glyphs.menu,
    tone: 'ink',
    nameAr: 'القائمة',
    nameEn: 'Menu',
    descAr: 'فتح قائمة التنقل على الموبايل',
    descEn: 'Open navigation on mobile',
    group: 'system',
  },
};

export function iconLabel(id: keyof typeof ICON_CATALOG, locale: 'ar' | 'en'): string {
  const item = ICON_CATALOG[id];
  return locale === 'en' ? item.nameEn : item.nameAr;
}
